### ISSUE TITLE
Failed to create redis cluster

### ISSUE THREAD

**Issue by wangke1020** [soarpenguin/redis-trib#2]
https://github.com/soarpenguin/redis-trib/blob/2b289d586850f5138c85e18dc298437c15231e21/clusternode.go#L271-L273
First command should be "CLUSTER INFO", but redigo does not support redis cluster(https://github.com/garyburd/redigo/issues/279). 
https://github.com/go-redis/redis may be a better choice.

**Comment by jwall149** [comment]
👍  For this issue, INFO in redis 4.x doesn't show cluster anymore...
