### ISSUE TITLE
Create cluster failure . Redis-4.0.7

### ISSUE THREAD

**Issue by hashwing** [soarpenguin/redis-trib#4]
```
[root@localhost redis-trib]# ./redis-trib create --replicas 1 127.0.0.1:30001 127.0.0.1:30002 127.0.0.1:30003 127.0.0.1:30004 127.0.0.1:30005 127.0.0.1:30006
INFO[0000] >>> Creating cluster                         
INFO[0000] >>> Performing hash slots allocation on 6 nodes... 
INFO[0000] Using 3 masters:                             
INFO[0000]   -> :0                                      
INFO[0000]   -> :0                                      
INFO[0000]   -> :0                                      
INFO[0000] Adding replica :0 to :0                      
INFO[0000] Adding replica :0 to :0                      
INFO[0000] Adding replica :0 to :0    

```

**Comment by soarpenguin** [comment]
$./redis-trib create --replicas 1 127.0.0.1:6380 127.0.0.1:6379 127.0.0.1:6378 127.0.0.1:7380 127.0.0.1:7379 127.0.0.1:7378
INFO[0000] >>> Creating cluster
INFO[0000] >>> Performing hash slots allocation on 6 nodes...
INFO[0000] Using 3 masters:
INFO[0000]   -> :0
INFO[0000]   -> :0
INFO[0000]   -> :0
INFO[0000] Adding replica :0 to :0
INFO[0000] Adding replica :0 to :0
INFO[0000] Adding replica :0 to :0
INFO[0000] M: 7503bf6c27718c391843e811d85da363dbd915fb :0
	   slots:10923-16383 (5461 slots) master
	   0 additional replica(s)
INFO[0000] S: 4d3ff27fcf80a46eb312686489cb4c396a71aa25 :0
	   replicates 5858ec206eaa4bd3b217092e4f401118dfd6de99
INFO[0000] S: 5d68114d874545b1b4a3eb49dc2e310e4d1bff11 :0
	   replicates 8258a1c2a222423642571bdb7f57c9a6de4d7ad4
INFO[0000] S: 73daf7fe396386a5a0c38b170dfc46fe567d7fcc :0
	   replicates 7503bf6c27718c391843e811d85da363dbd915fb
INFO[0000] M: 5858ec206eaa4bd3b217092e4f401118dfd6de99 :0
	   slots:0-5460 (5461 slots) master
	   0 additional replica(s)
INFO[0000] M: 8258a1c2a222423642571bdb7f57c9a6de4d7ad4 :0
	   slots:5461-10922 (5462 slots) master
	   0 additional replica(s)
Can I set the above configuration? (type 'yes' to accept): yes
INFO[0013] >>> Nodes configuration updated
INFO[0013] >>> Assign a different config epoch to each node
14647:M 13 Feb 14:12:58.418 # configEpoch set to 4 via CLUSTER SET-CONFIG-EPOCH
14646:M 13 Feb 14:12:58.418 # configEpoch set to 5 via CLUSTER SET-CONFIG-EPOCH
14645:M 13 Feb 14:12:58.418 # configEpoch set to 6 via CLUSTER SET-CONFIG-EPOCH
INFO[0013] >>> Sending CLUSTER MEET messages to join the cluster

INFO[0014] Waiting for the cluster to join
INFO[0014] >>> Performing Cluster Check (using node :0).
INFO[0014] M: 7503bf6c27718c391843e811d85da363dbd915fb :0
	   slots:10923-16383 (5461 slots) master
	   0 additional replica(s)
INFO[0014] S: 4d3ff27fcf80a46eb312686489cb4c396a71aa25 :0
	   replicates 5858ec206eaa4bd3b217092e4f401118dfd6de99
INFO[0014] S: 5d68114d874545b1b4a3eb49dc2e310e4d1bff11 :0
	   replicates 8258a1c2a222423642571bdb7f57c9a6de4d7ad4
INFO[0014] S: 73daf7fe396386a5a0c38b170dfc46fe567d7fcc :0
	   replicates 7503bf6c27718c391843e811d85da363dbd915fb
INFO[0014] M: 5858ec206eaa4bd3b217092e4f401118dfd6de99 :0
	   slots:0-5460 (5461 slots) master
	   0 additional replica(s)
INFO[0014] M: 8258a1c2a222423642571bdb7f57c9a6de4d7ad4 :0
	   slots:5461-10922 (5462 slots) master
	   0 additional replica(s)
INFO[0014] [OK] All nodes agree about slots configuration.
INFO[0014] >>> Check for open slots...
INFO[0014] >>> Check slots coverage...
INFO[0014] [OK] All 16384 slots covered.


my redis version is 4.0.2, i will test 4.0.7, tks

**Comment by PoplarYang** [comment]
I meet the same problem on Redis server v=4.0.12, Is this solved?
